#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 15 15:45:36 2022

@author: dorus
"""

from Bserie_pol import kt_co, kt_pow, kq_co, kq_pow
import numpy as np

def WageningenB(j, pd, EAR, z):
    kt_s, kt_t, kt_u, kt_v = kt_pow[:,0], kt_pow[:,1], kt_pow[:,2],kt_pow[:,3]
    kq_s, kq_t, kq_u, kq_v = kq_pow[:,0], kq_pow[:,1], kq_pow[:,2],kq_pow[:,3]
    
    K_sub_T = 0
    for idx in range(len(kt_co)):
        K_sub_T += kt_co[idx] * j ** kt_s[idx] * pd ** kt_t[idx] * EAR ** kt_u[idx] * z ** kt_v[idx]
    
    K_sub_Q = 0 
    for idx in range(len(kq_co)):
        K_sub_Q += kq_co[idx] * j ** kq_s[idx] * pd ** kq_t[idx] * EAR ** kq_u[idx] * z ** kq_v[idx]

    eta_O = j * K_sub_T / (K_sub_Q * 2 * np.pi)
    
    return K_sub_T, K_sub_Q, eta_O
    
